name: Notion to GitHub MD test

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 저장소 체크아웃

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Node.js 설정
        with:
          node-version: '16'  # 원하는 Node.js 버전을 선택

      - name: Install dependencies
        run: | # package-lock.json을 사용하여 종속성 설치
          npm install

      - name: Build TypeScript
        run: npm run build  # TypeScript 파일 빌드 스크립트 실행

      - name: Run TypeScript
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: node build/app.js  # 빌드된 JavaScript 파일 실행

      - name: Clone target repository
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          REPO=$(echo $CONFIG | jq -r '.github.repository')
          DIRECTORY=$(echo $CONFIG | jq -r '.github.directory')
          if [ -f "res/message.txt" ]; then
            MESSAGE=$(cat res/message.txt)
          fi
          git clone https://${{ secrets.TOKEN }}@github.com/${{ github.actor }}/$REPO.git
          mkdir -p $REPO/$DIRECTORY
          cp res/md/* $REPO/$DIRECTORY
          cd $REPO
          git config user.name 'notion-to-github-bot'
          git config user.email 'notiontogithubbot@gmail.com'
          if [[ -n $(git status --porcelain) ]]; then
            # 변경 내용이 있는 경우 커밋
            git add .
            git commit -m $MESSAGE
            echo "포스팅 되었습니다."
            git push
          else
            # 변경 내용이 없는 경우 에러 처리
            echo "포스팅 할 글이 없습니다."
          fi